# Generated by Django 3.0.1 on 2020-01-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
