# Generated by Django 3.0.1 on 2020-01-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0003_journal_room_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
